$(document).ready(function(){
    var menu_x=function(){
        $('.menu_icon').children('p').eq(0).css({transform:'translateY(-10px)'}).end()
        .siblings('p').eq(1).css({transform:'translateY(-10px)'}).end()
        .siblings('p').eq(2).css({transform:'translateY(-10px)'}).end()
        .siblings('p').eq(3).css({transform:'translateX(-10px)'}).end()
        .siblings('p').eq(4).css({opacity:'0%'}).end()
        .siblings('p').eq(5).css({transform:'translateX(10px)'}).end()
        .siblings('p').eq(6).css({transform:'translateY(10px)'}).end()
        .siblings('p').eq(7).css({transform:'translateY(10px)'}).end()
        .siblings('p').eq(8).css({transform:'translateY(10px)'}).end()
        .siblings('span').css({opacity:'100%',borderRadius:'10px'})
        .siblings('span').eq(0).css({top:'0',height:'88%'}).end()
        .siblings('span').eq(1).css({left:'0',width:'88%'}).end();
    }
    var menu_o=function(){
        $('.menu_icon').children('p').eq(1).css({transform:'translateY(0)'}).end()
        .siblings('p').eq(3).css({transform:'translateX(0)'}).end()
        .siblings('p').eq(4).css({opacity:'100%'}).end()
        .siblings('p').eq(5).css({transform:'translateX(0)'}).end()
        .siblings('p').eq(7).css({transform:'translateY(0)'}).end()
        .siblings('span').css({opacity:'0',borderRadius:'100%'})
        .siblings('p').eq(0).css({transform:'translateY(0)'}).end()
        .siblings('p').eq(2).css({transform:'translateY(0)'}).end()
        .siblings('p').eq(6).css({transform:'translateY(0)'}).end()
        .siblings('p').eq(8).css({transform:'translateY(0)'}).end();
    }
    $('.moon').click(function(){
        if($('body').css({background})=='#FFF3FE'){
            $('body').css({background:'#222'});
        }
    })
    $('.menu_icon').mouseenter(function(){
        if($('.menu_list').css('display')=='none'){
            menu_x();
        }else{
            menu_o();
        }
    })
    $('.menu_icon').mouseleave(function(){
        if($('.menu_list').css('display')=='none'){
            menu_o();
        }else{
            menu_x();
        }
    })
    $('.menu_icon').click(function(){
        if($('.menu_list').css('display')=='none'){
            $('.menu_list').show().find('span').stop().animate({top:'0px'},function(){
                menu_x();
                $('.menu_icon').animate({rotate:'45deg'}).children('p').eq(0).css({transform:'translateY(-10px)'}).end()
                .siblings('p').eq(2).css({transform:'translateY(-10px)'}).end()
                .siblings('p').eq(6).css({transform:'translateY(10px)'}).end()
                .siblings('p').eq(8).css({transform:'translateY(10px)'}).end()
            });
            $('.jelly').animate({width:'20%',height:'100%'}).children('img').eq(0).stop().animate({top:'35%',left:'5%',transform:'rotate(0)'}).end()
            .eq(1).stop().animate({top:'40%',left:'5%',transform:'rotate(0deg)'}).end()
            .eq(2).stop().animate({top:'50%',left:'5%',transform:'rotate(0deg)'}).end()
            .eq(3).stop().animate({top:'50%',left:'10%',transform:'rotate(0)'}).end()
            
        }else if($('.menu_list').css('display')=='block'){
            $('.menu_list').find('span').stop().animate({top:'-110px'},function(){
                menu_o();
                $('.menu_list').hide();
                $('.menu_icon').stop().animate({rotate:'0deg'}).children('p').eq(0).css({transform:'translateY(0)'}).end()
                .siblings('p').eq(2).css({transform:'translateY(0)'}).end()
                .siblings('p').eq(6).css({transform:'translateY(0)'}).end()
                .siblings('p').eq(8).css({transform:'translateY(0)'}).end()
            });
            $('.jelly').animate({width:'100%',height:'100%'}).children('img').eq(0).stop().animate({top:'-5%',left:'65%',transform:'rotate(-40deg)'}).end()
            .eq(1).stop().animate({top:'-30%',left:'0%',transform:'rotate(-60deg)'}).end()
            .eq(2).stop().animate({top:'65%',left:'2%',transform:'rotate(-130deg)'}).end()
            .eq(3).stop().animate({top:'75%',left:'80%',transform:'rotate(-40deg)'}).end()
        }
    })


})